[package]
name = "youp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
chrono = { version = "0.4" }
colored = { version = "2.1" }
tokio = { version = "1.40", features = ["full"] }
reqwest = { version = "0.12", features = ["blocking"] }
